name: Build Pre-release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for commit messages & git tagging

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install depedencies and build EXE
        run: python builder.py

      - name: Check
        id: check
        run: |
          $msg = git log -1 --pretty=%B
          echo "Commit message: $msg"
          if ($msg -like "*release*") {
            echo "should_release=false" >> $env:GITHUB_OUTPUT
          } else {
            echo "should_release=true" >> $env:GITHUB_OUTPUT
          }

      - name: Tag em
        if: steps.check.outputs.should_release == 'true'
        run: |
          $tag = "pre-v$(Get-Date -Format 'yyyy.MM.dd-HHmm')"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $tag
          git push origin $tag
          echo "tag=$tag" >> $env:GITHUB_ENV

      - name: Upload
        if: steps.check.outputs.should_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag }}
          name: ${{ env.tag }}
          prerelease: true
          files: dist/PTSaveFileEditor.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
